In [50]:
import fitz
import pandas as pd
import numpy as np
import json

from sklearn.metrics.pairwise import cosine_similarity

from ollama import chat
from ollama import embed

In [51]:
import os
os.makedirs("../outputs", exist_ok=True)

In [2]:
pdf_path = r"C:\Users\Hp\Desktop\Data Analysis with AI\Assignment 1\uzbekistan2006en.pdf"

doc = fitz.open(pdf_path)

text = ""

for page in doc:
    text += page.get_text()

print("Text length : ", len(text))
print(text)

Text length :  429192
2
UNDP is the UN’s global development network, advocating for change and connecting countries to knowledge, experience
and resources to help people build a better life. We are on the ground in 166 countries, working with them on their own solu-
tions to global and national development challenges. As they develop local capacity, they draw on the people of UNDP and
our wide range of partners.
© Report materials can not be reproduced in whole or in part, without prior permission of UNDP.
The analysis and recommendations expressed in this report do not necessarily represent the views of UNDP. This Report is an
independent publication produced by groups of experts commissioned by UNDP.
© United Nations Development Program
Сountry Office for Uzbekistan
700029 Tashkent , Shevchenko str,  4
Tel: + 998 71 120 34 50
Fax: + 998 71 120 34 85
www.undp.uz

National Human Development Report 2006: Health For All

NATIONAL HUMAN DEVELOPMENT REPORT TEAM
TEAM LEADERS
Galina Saidova
Damin Asadov
AUTORS
Fikret Akcura
Dilorom Ahmedova
Parahat Menlikulov
Nargiza Khodjaeva
Klara Yadgarova
Tatyana Motornyuk
Zavihulla Nasretdinkhodjaev
Raisa Zadorojnaya
Shukhrat Irgashev
Davron Mirtodjiev
STATISTICAL DATA
Reyganat Makhmudova
Irina Gorbunova
INTERNATIONAL CONSULTANT
Theodor Herzl Tulchisky
TEAM COORDINATOR
Kamola Safaeva
EDITOR
William Putnam
TRANSLATORS
Akhror  Askarov
Nataliya Gamiyans
LAYOUT DESIGN
Suren Sapov
COVER DESIGN
Babur Ismailov

ACKNOWLEDGEMENTS
This National Human Development Report was made possible through the support, assistance and valuable con-
tributions of many entities and individuals.
Special thanks for substantial support and assistance should go to Mr. Fikret Akcura, UN RC and UNDP
Resident Representative in Uzbekistan.
Exceptionally useful comments and recommendations were provided by the UN agencies: the authors express
their thanks to Mr. Reza Hossaini, Mr. Martin Raiser, Ms. Doina Bologa, Mrs. Nargiza Juraboeva, Mr. Andro
Shilakadze, Mr. Fuad Aliev, Mrs. Laura Rio, Mr. Aziz Khudoberdiev, Mr. Evgeniy Abdullaev and Ms. Nigina
Baykabulova for their invaluable contributions.
Thanks are also extended to the State Committee on Statistics, UN Agencies for statistical data and to Consumer
Rights Federation of Uzbekistan for research materials.
A significant contribution to the preparation and revision of the Report’s outline was made by the participants of
a roundtables held in Tashkent in October and December 2005 and June 2006. The authors would like to thank
all participants for the constructive discussions and for their recommendations.
Special thanks from the Report’s Coordinator go to Ms. Zhanara Sagimbayeva, Ms. Victoria Anoshkina and also
to the entire staff of the Business Center of UNDP CO Uzbekistan for their support and help.

National Human Development Report 2006: Health For All

FOREWORD
The 2006 National Human Development Report (NHDR) continues the tradition of UNDP’s annual analysis of
overall human development in the country, while also focusing on a selected priority area of Uzbekistan’s socio-
economic development.  This year, we have taken up health since the National Health Sector Reform Program
(1999-2005) just ended, providing a timely opportunity to review its accomplishments.  Moreover, many of the
Millennium Development Goals (MDGs) cover the health field and the interim Welfare Improvement Strategy of
the Government strongly emphasizes the health sector.
When compared with the health indicators for countries of similar GDP per capita, Uzbekistan’s health situation
looks admirable. However, when viewed against the Government’s ambitious living standards for the citizens, it
is clear that there is much to accomplish in the coming years.
In its first four chapters, the report contains an excellent description and analysis of recent human development
trends in Uzbekistan, and relates the national health indicators to the overall human development indicators.
That is followed by a discussion of the MDGs in Uzbekistan, the primary challenges that lie before the nation
until 2015, and the Government’s current efforts to achieve them.
The report’s recommendations mainly focus on public healthcare, including proposals for the next phase of
health sector reform, the role of the public and private sectors in those reform efforts, the need to increase public
oversight and improving the quality of the healthcare services provided to the people of Uzbekistan.
This report owes a great deal to the collaboration of the many ministries, departments, academic establishment
and individuals.  In that regard, I would especially thank the Ministry of Economy, the Ministry of Health and
the State Comity of Statistics. Moreover, the entire UN system and the donor community also provided very
valuable inputs.
I would like to express UNDP’s special gratitude to Mrs. Saidova, the First Deputy Minister of Economy, who led
a very talented team of national authors, resulting in a comprehensive report that clearly identifies the achieve-
ments of Uzbekistan, as well as the remaining challenges that require the close collaboration of the Government,
the private sector, the civil society, and the donor community. I would also like to thank Dr. Kamola Safaeva for
her dedication and able management of the entire 2006 NHDR preparation for UNDP.
Fikret Akcura
UNDP Resident Representative
ABBREVIATIONS LIST
ABD
—	 Asian Bank of Development
CIDA
—	 Canadian International Development Agency
CIS
—	 Commonwealth of Independent States
CRFU
—	 Consumer Rights Federation of Uzbekistan
CSW
—	 Commercial sex workers
DOTS
—	 Directly Observed Treatment, Short-course
GDP
—	 Gross National Product
GP
—	 General practitioner
HD
—	 Human Development
HDI
—	 Human Development Index
HDR
—	 Human Development Report
HLS
—	 Healthy lifestyle
IDU
—	 Injecting drug users
IMF
—	 International Monetary Fund
JICA
—	 Japan International Cooperation Agency
MDG
—	 Millennium Development Goals
MSM
—	 man sleeping with man
PHC
—	 Public health care
RSELS
—	 Regional strategies for enhancement of living standards
STI
—	 Sexually transmitted infections
SVP
—	 Rural outpatient posts
TB
—	 Tuberculosis
UNAID
—	 Joint UN Programme on HIV/AIDS
UNDP
—	 United Development program
UNFPA
—	 United Nations Population Fund
UNICEF
—	 United Nations Children’s Fund
UNODC
—	 United Nations Office on Drugs and Crime
USAID
—	 United States Agency for International Development
USSR
—	 Union of Soviet Social Republics
UzMoH
—	 Ministry of Health of Uzbekistan
WB
—	 World Bank
WHO
—	 World Health Organization
WISP
—	 Welfare Improvement Strategy Programme

CONTENTS
Executive Summary...................................................................................................................................... 8
Chapter 1.	 The Status of Human Development in Uzbekistan.........................13
1.1	 The current human development situation ................................................................. 13
1.2	 Health as a Key Prerequisite for Human Development.............................................. 22
Chapter 2.	 Health and the Millennium Development Goals..............................26
2.1	 Efforts to Achieve the MDG in Uzbekistan  .................................................................. 26
2.2	 Impact of Nutrition on Population Health..................................................................... 28
2.3	 Reproductive health............................................................................................................ 31
2.4	 Child Health Care.................................................................................................................. 35
2.5	 AIDS, TB, Viral Hepatitis....................................................................................................... 40
2.6	 Environment and Health.................................................................................................... 46
Chapter 3.	 Public Health in Uzbekistan..................................................................................50
3.1	 Health Status......................................................................................................................... 50
3.2	 Determinants of Health...................................................................................................... 54
Chapter 4.	 The Health Care Outlook in Uzbekistan....................................................64
4.1	 Health Care Reform.............................................................................................................. 64
4.2	 Roles of the public and private sectors in health care............................................... 71
4.2	 Health care financing.......................................................................................................... 86
4.3	 Enhance the quality of medical assistance................................................................... 91
Legislative Basis of the System of Health Care.................................................................94
Statistical Tables............................................................................................................................................96

National Human Development Report 2006: Health For All
 The era of globalization has paved the way for a giant
positive leap forward in high technology and in the
development of world trade and investment. Today’s
generation in every country of the world has hopes
that it will be richer, better educated and healthier
than previous generations were. Progress is being
made practically all over the world in resolving the
problems of primary education and reducing infant/
child mortality.  Human life expectancy is increasing.
Despite the benefits of globalization, however, prob-
lems in eliminating the gap between rich and poor
countries still exist, while the gap in some countries
is even widening.  At the same time, poverty is not
the only threat to progress in human development.
The worldwide spread of dangerous diseases, e.g.
HIV/AIDS, TB, and avian flu, poses another danger-
ous threat to progress in human development.
The main objective of human development is to create
an environment that politically, economically, socially,
culturally and ecologically is conducive to promoting
the public welfare while providing everyone with the
opportunity to enjoy a long, healthy and productive
life.
This Annual Report on Human Development in the
Republic of Uzbekistan focuses on one of the key indi-
cators which reflects the essence of human existence
and development, namely, health status. The Report
consists of four chapters which describe and analyze
general human development trends in the Republic
of Uzbekistan while pointing out how the country’s
health indicators and other human development
indicators are interrelated. A special chapter titled
Millennium Development Goals (MDG) focuses on
the problems the Republic of Uzbekistan faces and on
the efforts the country is making to achieve the MDG.
The authors of the Report devote particular attention
to public health care development, health status and
to the factors that determine the nation’s health status.
The report concludes, logically, with a chapter analys-
ing the prospects for public health care development,
including the strategy for health care reform, the role
of the public and private sectors in developing the
health care system and improving the quality of the
health care services the system provides the people of
Uzbekistan.
Chapter 1. Human Development and Health
Thanks to the economic reforms the Government
of Uzbekistan carried out in 2005, the Republic of
Uzbekistan experienced a 7% growth rate in GDP for
the second year in a row.  Growth rates in industry,
agriculture and other branches of the economy were
even greater.  The rate of growth of the small enter-
prise sector went above the 25% point, while domestic
trade and export indicators experienced growth rates
of 10-15%.
Thanks to the reforms, annual per capita income grew
by 22% as well. Social infrastructure is undergoing
dynamic development: the number of schools, voca-
tional colleges, academic lyceums, rural doctor’s sta-
tions and other health care institution buildings built
or renovated increased. Progress is being made in
providing the public with safe drinking water. State
budget expenditures for social programmes exceeded
50%, while growing public revenues ensured a bal-
anced budget.
For the past decade the Human Development Index
(HDI) has been increasing in all of the world’s devel-
oping regions, although at varying rates. However,
the HDI in 18 countries, with a combined population
of 460 million people, was lower in 2003 than it was
in 1990.  Six of those 18 countries are former Soviet
Republics.
Uzbekistan’s HDI is growing constantly.  In 2004 its
HDI was 0.756 compared with 0.747 in 2003.  Thanks
to positive social and economic development, the
Republic of Uzbekistan maintained that trend in
2005 and thanks to educational reforms,  Uzbekistan’s
already rather high indicators for the number of years
of education completed and for the literacy rate also
increased.  Life expectancy at birth reached 72.5 years,
an average increase of not quite (0.9) one year.
The Republic of Uzbekistan’s indicators for educational
development and life expectancy at birth are very close
to those of countries with a high HDI. It is unfortu-
nate, therefore, that Uzbekistan’s low per capita GDP
has kept it from being added to the list of high HDI
countries.
Economic growth is one of the factors that make it
possible to provide  easier access to quality health care
services. By the same token, it is also true that a society
whose population is not healthy and does not repro-
Executive Summary


National Human Development Report 2006: Health For All
duce itself is unable to sustain a high rate of economic
development and improve its people’s well-being. As
an indicator of the level, mode and quality of human
life, health status is linked very closely to the MDGs.
Public health, as well as individual health, are state
strategy goals and a prerequisite for national security.
Public health is known to be a necessary condition of
maintenance of healthy human resources in the coun-
try and a criterion of efficacy of state management.
The quality of people’s health is closely associated
with poverty level. There is a vicious circle: “poor
family – poor health, poor health – poor family”.
The vicious circle can be broken only with state sup-
port. Government can help poor families to improve
their health by developing a health care system giv-
ing family members broad access to health care ser-
vices. Improved health contributes to increased labour
productivity and helps the poor to break the cycle of
poverty.
Public and individual health, along with growth of a
country’s economic resources, creates job opportuni-
ties and improves well-being. Education has a direct
influence on the individual’s attitude to his/her health.
Educated people are more health conscious, make
more effective use of preventive measures, are more
likely to practice a healthy life style and quick to notice
disease, and able to give themselves first aid and to
seek quality health care services.
The environment and living conditions have a
direct impact on the health status of the public.
Environmental degradation can harm not only the
health of those alive today but can also inflict harm
future generations by damaging the gene pool.
Chapter 2.  Health and the Millennium
Development  Goals
The Millennium Declaration drew up a global agenda
for the 21st century and set action-oriented goals
known as Millennium Development Goals (MDGs).
By 2015 eight MDGs are to be achieved at the global,
regional and national levels, using special indicators to
measure achievement.
The first seven MDGs goals aim to reduce poverty in
all its manifestations. The eighth provides the means
to achieve the first seven and calls upon developed
countries to take action to further reduce the debt of
poor countries and to contribute to the development
of low-income countries.
As a signatory to the Millennium Declaration,
Uzbekistan has made significant strides to meet its
MDG commitments.  The Government of Uzbekistan
realizes the urgency of these commitments and their
relationship to its national development.
By 2015 the poverty level is expected to be cut in half
compared with 2001, i.e., reduced to 14%. The data
for 2003-2004 are encouraging: each year the poverty
index went down by over 1 percentage point.
In the Republic of Uzbekistan, all children in all prov-
inces obtain an 11- to 12-year secondary education.
Many schools, colleges and lyceums are built each
year.  Over 59,600 students were enrolled in institu-
tions of higher education in 2005, of which 54,200
were enrolled in bachelor’s degree programs and 5,400
in master’s degree programs, representing an increase
of 1.33 times over enrolment in 2000. A positive trend
is observed in enrolment of women in Uzbekistan’s
institutions of higher education: the number of women
admitted has increased by 44.3%, while the number of
men enrolled has increased by 26.8 per cent.
In 2004 infant mortality was reduced by 22%.
Mortality among children under 5 years of age was
22% lower than in the baseline year. The rate of mater-
nal mortality has gone down by 7%.
Some success was achieved in slowing the explosive
growth of the number of HIV/AIDS patients (109% in
2005 compared with 187% in 2003).
 After increasing for seven years straight, the tubercu-
losis prevalence rate began a downward trend accord-
ing to the WHO Global Report. In 2004 the TB rate
was 75.8 ppm (per 100 000 of population) compared
with 80 ppm in 2002.  Over 80% of Uzbekistan’s pop-
ulation now has access to DOTS programmes. A few
cases of malaria have recently been reported in the
country.
In 2004 the share of the population provided with safe
drinking water increased 3.4 times to 83.8%.  In rural
areas, this indicator increased from 71.0% to 78.5%.
Some 40% of the urban and 5% of the rural popula-
tion have better sanitary and hygienic conditions
now. The Government of the Republic of Uzbekistan,
in collaboration with the ABD, UN and World Bank
in 2004 formulated a Welfare Improvement Strategy
for of the Population (WISP) of Uzbekistan between
2005 and 2010 which sets priorities linked closely to
Uzbekistan’s MDGs. The Republic of Uzbekistan must
work very hard to improve the structure of its people’s
nutrition, in particular, to offset micronutrient defi-
ciencies (iodine, iron, vitamin A).
Many problems regarding the protection of women’s
reproductive health remain. Although rates of mater-
nal and infant mortality are decreasing in compari-
son with those of developed countries, maternal and
infant mortality remain relatively high in Uzbekistan.
Maternal and child health were improved by: imple-
mentation of comprehensive programmes for the
improvement of the health of women of reproductive
10
age and of children;  setting up special prevention and
treatment centres for mothers and children in hos-
pitals/out-patient clinics; providing better access to
various modern contraceptives; and encouragement of
longer spacing between births.
Expert data indicate that achieving the MDG infant
mortality reduction target is a fully feasible and
manageable process.  A decrease in infant mortality
depends, first of all, upon: the quality of health care
services provided during labour and the first days of
a newborn’s life; improvement of health care work-
ers’ skills;  and providing health care facilities with the
necessary equipment.
Implementation
of
the
Women
and
Younger
Generation Health Improvement Project, a USD 40
million project funded by the ABD, was begun in
2005. Under the Project, newborn resuscitation units
in central district hospitals and provincial maternity

In [3]:
def create_chunks(text,
                  chunk_size=1500,
                  overlap=200):

    chunks = []

    start = 0

    while start < len(text):

        end = start + chunk_size

        chunks.append(text[start:end])

        start += chunk_size - overlap

    return chunks

In [4]:
chunks = create_chunks(text)

print("Chunks : ", len(chunks))

Chunks :  331

In [5]:
from ollama import embed

response = embed(
    model="nomic-embed-text",
    input=chunks[0]
)

print(len(response["embeddings"][0]))

768

In [6]:
embeddings = []

for chunk in chunks:

    e = embed(
        model="nomic-embed-text",
        input=chunk
    )

    embeddings.append(e["embeddings"][0])

In [ ]:
embeddings = np.array(embeddings)

In [48]:
retrieve(
    "health reforms in Uzbekistan"
)

['public of Uzbekistan of 25.01.2005  No 30 “On  State \nProgramme “The Year of Health”\nOrdinance of the Cabinet of Ministers of the Republic of Uzbekistan of 21.12.2005  No 276 “On approv-\ning the improved system of remuneration of labour of health providers” \nOrdinance of the Cabinet of Ministers of the Republic of Uzbekistan of 28.09.2005  No 217 “On measures \nto further reform  the system of financing and managing health care institutions in the Republic of \nUzbekistan” \nOrdinance of the Cabinet of Ministers of the Republic of Uzbekistan of 08.06.2004  No 264 “On measures \nto complete the experiment and extend reforms in the health care system” \nOrdinance  of the Cabinet of Ministers of the Republic of Uzbekistan of 23.04.2004  No 195 “On mea-\nsures to further develop the   Public System “Mother and Child Screening” \nOrdinance of the Cabinet of Ministers of the Republic of Uzbekistan of 25.08.2003  No 365 “  On \napproval of the Statute on medical examination of people who want to get married” \n1.\n2.\n3.\n4.\n5.\n6.\n7.\n8.\n9.\n10.\n11.\n1.\n2.\n3.\n4.\n5.\n6.\n7.\n8.\n9.\n10.\n11.\n12.\n13.\nLegislative Basis of the System of Health Care\n94\nOrdinance of  the Cabinet of Ministers of the Republic of Uzbekistan of 05.07.2002  No 242 “On mea-\nsures to follow the priority course of fostering health care culture in family, improving   women health, \nbirth and upbringing healthy generation”  \nOrdinance of the Cabinet of Ministers of the Republic of Uzbekistan of 25.01.2002  No 32 “On additional \nmeasure',
 'e services.  To date, four national \nspecialized centers for surgery, cardiology, urology, \nand microsurgery, respectively, have been established \nin Uzbekistan.\nUzbekistan’s current health care system is unique in \nthat it retains features of the Soviet health care system \ncombined with elements typical of modern health care \nreforms.\n•\n•\n•\n•\nIn building the new health care system, the \nGovernment of Uzbekistan has been guided by the fol-\nlowing principles and precepts:\nFor human development purposes, health care \nmust be accessible to all population groups. There \nmust be unlimited access to primary health care \nwhich must be free-of-charge, even in a market \neconomy;\nResidence in rural areas must not negatively \nimpact human capacity development.  The previ-\nous system of rural primary health care services \nprovided by medical attendants (feldshers) resulted \nin discrimination against the rural population, \ncompared with the urban population.  Therefore, \nimprovement of the quality of rural health care \nservices is the centerpiece of the new health care \nsystem.  Under the new system, new health care \ninstitutions – rural doctors’ posts -- are being \ncreated, at which medical assistance provided by \nmedical attendants is being replaced by medical \nassistance provided by qualified health care staff \nwith medical university degrees.\n•\n•\nBox 4.1\n2006 - the Year of Charity and Health Workers\nGoals \nImplements integrated goal- and target-oriented functions that:\nEnhance the rol',
 'ies as well as media representatives \nHence, preventive health care, the healthy life-style \nconcept, and improvements in the quality of health \ncare services constitute the strategic triad for develop-\ning a health care system designed to improve public \nhealth in Uzbekistan in the 21st century.\n•\n•\n•\n94\nList of laws of the Republic of Uzbekistan on Health Care\nConstitution of the Republic of Uzbekistan, clause 40\nLaw  of the Republic of Uzbekistan of 29.08.1996 No 265-I “On Health Care of Citizens” \nof the Republic of Uzbekistan of 03.07.1992  No 657-XII “On the Public Sanitary Surveillance” \nLaw of the Republic of Uzbekistan of 09.12.1992   No 753-XII “On compulsory treatment of patients with \nchronic alcohol or drug addiction”\nLaw of the Republic of Uzbekistan of 19.08.1999  No 813-I “On narcotic drugs and psychotropic \nsubstances”\nLaw of the Republic of Uzbekistan of 25.04.1997 No 415-I “On medicines and pharmaceutical activity”\nLaw of the Republic of Uzbekistan of 31.08.2000  No 123-II “On mental health care”\nLaw of the Republic of Uzbekistan of 11.05.2001  No 215-II “On protection of population against \ntuberculosis”\nLaw of the Republic of Uzbekistan of 19.08.1999  No 816-I “On prevention of disease caused by human \nimmunodeficiency virus (HIV)”\nLaw of the Republic of Uzbekistan of 30.08.2002  No 402-II “On donating blood and its components”\nLaw of the Republic of Uzbekistan of 30.08.1997 “On quality and safety of foodstuffs” \nDecrees and Ordinances of the President of']

In [49]:
context = "\n".join(
    retrieve(
        "health reforms in Uzbekistan"
    )
)

In [12]:
prompt = f"""
Using ONLY the context below.

Summarise the health reforms.

Context:

{context}
"""

In [13]:
response = chat(
    model="llama3.2",
    messages=[
        {
            "role":"user",
            "content":prompt
        }
    ]
)

print(response["message"]["content"])

Unfortunately, there is no mention of "health reforms" in the provided context. However, based on the information about the health care system and laws related to it, I can summarize some key aspects of the system:

* The health care system in Uzbekistan combines features of the Soviet health care system with modern elements.
* One of the primary goals is to ensure unlimited access to primary health care services for all population groups, including rural areas.
* Rural health care services were previously provided by medical attendants (feldshers), but under the new system, qualified health care staff with medical university degrees will provide assistance in these areas.
* There are laws and regulations related to various aspects of health care, such as mental health care, prevention of disease caused by HIV, and protection against tuberculosis.

If you're looking for information on specific "health reforms," I would need more context or information about what you mean by "reforms."

In [14]:
from ollama import chat

def ask_llm(prompt, model="llama3.2"):
    
    response = chat(
        model=model,
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )

    return response["message"]["content"]

In [15]:
chapter_query = "Chapter 1 human development"

retrieved_chunks = retrieve(
    chapter_query,
    top_k=5
)

retrieved_context = "\n".join(
    retrieved_chunks
)

In [16]:
summary_prompt = f"""
You are a UN development analyst.

Using ONLY the provided context.

Provide:

1. Executive summary (150 words maximum)

2. Five key findings

3. Five key policy priorities

Context:

{context}
"""

In [17]:
report_summary = ask_llm(summary_prompt)

In [18]:
chapter_summaries = {}

chapter_queries = {
    "Chapter 1": "human development in Uzbekistan",
    "Chapter 2": "health situation in Uzbekistan",
    "Chapter 3": "healthcare reforms in Uzbekistan",
    "Chapter 4": "millennium development goals Uzbekistan"
}

for chapter, query in chapter_queries.items():

    retrieved_context = "\n".join(
        retrieve(query, top_k=5)
    )

    prompt = f"""
    You are a UN development analyst.

    Summarise this chapter in less than 100 words.

    Focus on:
    - key findings
    - health outcomes
    - development challenges
    - important policies

    Context:
    {retrieved_context}
    """

    summary = ask_llm(prompt)

    chapter_summaries[chapter] = summary

In [19]:
for chapter, summary in chapter_summaries.items():
    print("\n" + "="*50)
    print(chapter)
    print("="*50)
    print(summary)

==================================================
Chapter 1
==================================================
Here is a summary of the chapter in less than 100 words:

Key findings:

* Uzbekistan's economic reforms have led to a 7% growth rate in GDP and increased per capita income.
* The Human Development Index (HDI) has been increasing, but six former Soviet Republics, including Uzbekistan, have lower HDI scores.

Health outcomes:

* Child mortality rates have decreased significantly since the mid-1990s.
* Mother and child health programs have been implemented to address specific health concerns.

Development challenges:

* The country still faces significant development challenges, including high infant and maternal mortality rates.

Important policies:

* Economic reforms aim to promote private sector growth and investment.

==================================================
Chapter 2
==================================================
Here is a summary of Chapter 3: Public Health Care in Uzbekistan:

**Key Findings:**

* The Republic of Uzbekistan has a relatively long life expectancy, with an average of 72.5 years in 2004.
* Morbidity rates are high for infectious and parasitic diseases, endocrine system disorders, blood and hemopoietic organ diseases, and mental diseases.
* Environmental factors, such as pollution, are significant contributors to health problems.

**Health Outcomes:**

* Life expectancy has increased over the past decade, but still lags behind other CIS countries.
* Diarrheal diseases and acute viral hepatitis remain major public health concerns.
* The incidence of infectious diseases has decreased thanks to improved access to clean water and sanitation.

**Development Challenges:**

* Limited resources for public health interventions, making it difficult to address all health problems simultaneously.
* Environmental protection and public health must be prioritized over other health issues.

**Important Policies:**

* A focus on family healthcare services is key to improving public health care.
* Building a strong emphasis on rural healthcare services will help address the country's rural-urban disparities in health outcomes.
* Improving professional working conditions for healthcare workers will also contribute to better public health outcomes.

==================================================
Chapter 3
==================================================
Here is a summary of the chapter in less than 100 words:

Key findings: Uzbekistan has established four national specialized centers for surgery, cardiology, urology, and microsurgery, and aims to improve rural healthcare services.

Health outcomes: The country's healthcare system retains features of the Soviet era, with limited access to primary care, especially in rural areas. There is a need for improved health infrastructure and training of healthcare staff.

Development challenges: The country faces challenges in providing universal access to healthcare, particularly in rural areas where medical attendants have historically provided services that are now being replaced by qualified healthcare staff.

Important policies:

1. Establishing new health care institutions – rural doctors’ posts – to improve quality of rural health care services.
2. Emphasis on primary health care, with general practitioners providing bulk of primary medical assistance.
3. Focus on early identification and prevention of birth defects and other health issues through the Mother and Child Screening program.

These policies aim to address the country's development challenges and improve healthcare outcomes for all population groups, particularly in rural areas.

==================================================
Chapter 4
==================================================
Here is a summary of Chapter 2: Health and the Millennium Development Goals in less than 100 words:

**Key Findings:** Uzbekistan has made significant strides to meet its MDG commitments, with efforts to reduce poverty, improve access to healthcare, and increase life expectancy.

**Health Outcomes:** Despite improvements, health challenges persist, including environmental degradation and limited access to clean water (72.2% of sources).

**Development Challenges:** The country faces significant development challenges, including a large proportion of children not completing secondary education, high infant mortality rates, and inadequate healthcare infrastructure.

**Important Policies:** The Government of Uzbekistan has formulated the Welfare Improvement Strategy Programme, which aims to improve living standards by increasing access to healthcare, education, and other essential services.

In [20]:
import json

with open("../outputs/chapter_summaries.json",
          "w",
          encoding="utf-8") as f:

    json.dump(
        chapter_summaries,
        f,
        indent=4,
        ensure_ascii=False
    )

In [21]:
theme_context = "\n".join(
    retrieve(
        "education health inequality economy gender climate employment",
        top_k=10
    )
)

theme_prompt = f"""
Analyse the report.

For each theme assign a score from 0 to 10.

Themes:

education
health
inequality
economy
gender
climate
employment

Return ONLY JSON.

Example:

{{
"education":8,
"health":10,
"inequality":6,
"economy":7,
"gender":5,
"climate":2,
"employment":4
}}

Context:
{theme_context}
"""

theme_scores = ask_llm(theme_prompt)

print(theme_scores)

{
"education":8,
"health":10,
"inequality":6,
"economy":7,
"gender":5,
"climate":2,
"employment":4
}

In [22]:
with open("../outputs/theme_scores.txt",
          "w",
          encoding="utf-8") as f:

    f.write(theme_scores)

In [23]:
strength_context = "\n".join(
    retrieve(
        "strengths challenges development achievements problems",
        top_k=10
    )
)

strength_prompt = f"""
Identify:

1. Development strengths (maximum 8)

2. Development challenges (maximum 8)

Return JSON only.

Context:

{strength_context}
"""

strengths_challenges = ask_llm(strength_prompt)

print(strengths_challenges)

```
{
  "development_strengths": [
    "Improvements in access to clean water",
    "Reduced child mortality rates",
    "Increased life expectancy",
    "Advances in education",
    "Growing income and economic growth",
    "Improved healthcare systems",
    "Enhanced social services",
    "Increased participation in sports and physical activities"
  ],
  "development_challenges": [
    "High levels of poverty and inequality",
    "Micronutrient deficiencies and malnutrition",
    "Environmental degradation and pollution",
    "Limited access to quality education",
    "Insufficient healthcare infrastructure",
    "Vicious cycle of poverty and poor health",
    "Lack of access to clean water and sanitation",
    "Inadequate healthcare services for vulnerable populations"
  ]
}
```

In [24]:
with open("../outputs/strengths_challenges.txt",
          "w",
          encoding="utf-8") as f:

    f.write(strengths_challenges)

In [25]:
indicator_context = "\n".join(
    retrieve(
        "HDI life expectancy literacy GDP population indicators",
        top_k=10
    )
)

indicator_prompt = f"""
Extract development indicators.

Return ONLY JSON.

{{
"HDI":"",
"Life_Expectancy":"",
"Literacy_Rate":"",
"GDP_Per_Capita":"",
"Population":"",
"GDI":"",
"Women_Empowerment_Index":""
}}

Context:

{indicator_context}
"""

indicators = ask_llm(indicator_prompt)

print(indicators)

{"HDI":0.694,"Life_Expectancy":"72.5","Literacy_Rate":"","GDP_Per_Capita":"","Population":"","GDI":"","Women_Empowerment_Index":""}

In [26]:
with open("../outputs/indicators.txt",
          "w",
          encoding="utf-8") as f:

    f.write(indicators)

In [27]:
models = [
    "llama3.2",
    "qwen2.5:3b",
    "phi3:mini"
]

model_outputs = {}

comparison_prompt = f"""
Summarise the main development findings
of the Uzbekistan 2006 report.

Context:

{context}
"""

for model in models:

    result = ask_llm(
        comparison_prompt,
        model=model
    )

    model_outputs[model] = result

    print("\n")
    print("="*50)
    print(model)
    print("="*50)
    print(result)

==================================================
llama3.2
==================================================
The 2006 report on Uzbekistan's health care system appears to be a comprehensive document that outlines the country's progress in improving its health care infrastructure. Based on the provided context, here are some key development findings from the report:

1. **Retaining features of Soviet and modern health care systems**: Uzbekistan's current health care system combines elements of both the Soviet and modern health care reforms.
2. **Improving access to primary health care**: The new health care system aims to provide unlimited access to primary health care, which is free-of-charge, even in a market economy.
3. **Enhancing rural health care services**: The report highlights the importance of improving the quality of rural health care services, particularly after the previous system's discrimination against rural populations.
4. **Creating new health care institutions**: New health care institutions, such as rural doctors' posts, are being established to provide medical assistance by qualified health care staff with medical university degrees.
5. **Promoting preventive health care and healthy lifestyle**: The strategic triad for developing a health care system in Uzbekistan includes enhancing preventive health care, promoting the healthy life-style concept, and improving the quality of health care services.

Some key legislative basis of the system include:

1. **Constitution of the Republic of Uzbekistan**: Clause 40
2. **Laws**:
	* Law No 265-I "On Health Care of Citizens" (1996)
	* Law No 657-XII "On the Public Sanitary Surveillance" (1992)
	* Law No 753-XII "On compulsory treatment of patients with chronic alcohol or drug addiction" (1992)
	* Law No 813-I "On narcotic drugs and psychotropic substances" (1999)
	* Law No 415-I "On medicines and pharmaceutical activity" (1997)
	* Law No 123-II "On mental health care" (2000)
	* Law No 215-II "On protection of population against tuberculosis" (2001)
	* Law No 816-I "On prevention of disease caused by human immunodeficiency virus (HIV)" (1999)
	* Law No 402-II "On donating blood and its components" (2002)
	* Law No 30 "On the Year of Health" (2005)

Overall, the report highlights Uzbekistan's efforts to improve its health care system, with a focus on increasing access to primary health care, enhancing rural health care services, and promoting preventive health care and healthy lifestyle.


==================================================
qwen2.5:3b
==================================================
The main development findings from the Uzbekistan 2006 report can be summarized as follows:

### Legislative Framework for Health Care
- **Legislative Basis:** A series of legislative measures were implemented in 2004, 2005, and 2006 to support and reform the health care system. These include:
  - Ordinance No 276 approving an improved system of remuneration for healthcare providers.
  - Ordinance No 217 outlining measures to further reform the financing and management of health care institutions.
  - Ordinances No 264, 195, and others addressing specific aspects such as public health systems, marriage medical examinations, rural healthcare, etc.

### Objectives and Principles
- **Human Development:** The primary goal was to ensure that all population groups have access to quality healthcare services, emphasizing accessibility for all.
- **Rural Healthcare Improvement:** Focus on improving the quality of healthcare in rural areas by establishing new institutions (rural doctors' posts) with qualified staff replacing medical attendants.

### Core Components and Strategies
- **Integrated Goal-Oriented Functions:** The health care system aimed to enhance roles, particularly focusing on preventive healthcare, healthy lifestyles, and improved service quality.
- **Strategic Triad for Public Health Improvement:** Preventive healthcare, healthy lifestyle concepts, and improvements in healthcare services formed the strategic foundation for developing a modern public health system.

### Legal and Regulatory Support
- **Constitutional and National Laws:** The report mentions several key laws including those on health care, sanitation surveillance, treatment of chronic addictions, narcotic substances, medicines, mental health, population protection against tuberculosis, HIV prevention, blood donation, and food safety.

These legislative measures and principles reflect the government's commitment to reforming the healthcare sector in line with modern standards while maintaining elements from the Soviet era. The focus on rural areas, improving access, and enhancing service quality were pivotal components of this ambitious health care system development strategy.

In summary, the report highlighted a comprehensive approach involving various legislative acts, specific reforms, and underlying principles designed to strengthen the Uzbekistan healthcare sector for public benefit in line with international standards.


==================================================
phi3:mini
==================================================
The main development findings from the Uzbekistan 2006 report on health care indicate a significant reform in their national system, which continues to incorporate elements of the Soviet model while adapting modern reforms. Key points include:

- Accessibility and equity have been emphasized as fundamental principles for human development purposes; primary health care must be universally accessible regardless of income level or location (urban vs rural). The aim is free access even in a market economy, focusing on preventive measures rather than financial barriers. This approach acknowledges the past issues where residing outside cities limited people's opportunities for comprehensive human development and well-being due to discrimination against non-residents by medical attendants (feldshers).

- To ensure rural populations are not disadvantaged, new institutions like rural doctors’ posts have been introduced. These replace existing feldshers with qualified staff holding university degrees in medicine and other relevant fields, which is expected to raise the standard of healthcare provided. This shift also reflects a broader strategy for decentralizing care closer to where people live while aiming to reduce disparities between urban-based medical services and rural accessibility.

- The strategic triad adopted includes preventive health care, fostering a culture promoting wellness as part of human development goals in Uzbekistan's 21st century context. Emphasizing the importance of quality primary healthcare is one pillar alongside media representation and professional involvement to raise awareness about public health matters nationally.

- Legislative frameworks like Ordinance No. 276 on remuneration for labor within Uzbekistan's health sector reflect a continuous effort toward incentivizing the workforce, which is crucial as it directly impacts service quality and availability to citizens. This ordinance demonstrates how financial motivations can help ensure an adequate supply of qualified personnel who are essential components for maintaining system performance standards across Uzbekistan's healthcare facilities.

- A series of Ordinances, starting from the Cabinet of Ministers in 2005 to as recent as July 2006, shows a sustained focus on improving financing and management for better care quality throughout various facets of Uzbekistan's healthcare system. These ordinances represent incremental steps towards modernizing not only the service delivery mechanisms but also enhancing strategic governance at both localized clinics/facilities (e.g., maternal-child screening and specialist centers) as well as overarching national systems for health care financing, organization of services in different regions like Bukhara province, Tashkent city, etc.

Overall, the report reflects a comprehensive approach to revitalizing Uzbekistan's public health sector through legislative reforms and new institutional arrangements with an eye towards improving accessibility for underserved communities while ensuring that human development is at its core guiding principle throughout these changes.

In [28]:
with open("../outputs/model_outputs.json",
          "w",
          encoding="utf-8") as f:

    json.dump(
        model_outputs,
        f,
        indent=4,
        ensure_ascii=False
    )

In [29]:
llama_output = model_outputs["llama3.2"]

evaluation_prompt = f"""
You are evaluating an AI-generated summary.

Source Context:

{context[:6000]}

Generated Summary:

{llama_output}

Score:

1. Consistency (1-5)
2. Completeness (1-5)
3. Factual Alignment (1-5)

Return JSON only.
"""

evaluation = ask_llm(
    evaluation_prompt,
    model="qwen2.5:3b"
)

print(evaluation)

{
  "consistency": 4,
  "completeness": 4,
  "factual_alignment": 4
}

In [30]:
with open("../outputs/evaluation.txt",
          "w",
          encoding="utf-8") as f:

    f.write(evaluation)

In [31]:
print(type(report_summary))
print(type(chapter_summaries))
print(type(theme_scores))
print(type(indicators))

<class 'str'>
<class 'dict'>
<class 'str'>
<class 'str'>

In [32]:
import os

os.makedirs("../outputs", exist_ok=True)

In [33]:
hdi_df = pd.DataFrame({
    "Year":[1995,2000,2001,2002,2003,2004],
    "HDI":[0.715,0.736,0.740,0.742,0.747,0.756]
})

life_df = pd.DataFrame({
    "Year":[1995,2000,2001,2002,2003,2004],
    "LifeExpectancy":[69.1,70.8,71.3,71.2,71.6,72.5]
})

gdi_df = pd.DataFrame({
    "Year":[1995,2000,2001,2002,2003,2004],
    "GDI":[0.704,0.729,0.734,0.738,0.742,0.752]
})

In [34]:
hdi_df.to_csv("../outputs/hdi_trend.csv",index=False)
life_df.to_csv("../outputs/life_expectancy.csv",index=False)
gdi_df.to_csv("../outputs/gdi_trend.csv",index=False)

In [35]:
comparison_df = pd.DataFrame({
    "Model":[
        "llama3.2",
        "qwen2.5:3b",
        "phi3:mini"
    ],
    "Output_Length":[
        len(model_outputs["llama3.2"]),
        len(model_outputs["qwen2.5:3b"]),
        len(model_outputs["phi3:mini"])
    ]
})

comparison_df

        Model  Output_Length
0    llama3.2           2380
1  qwen2.5:3b           2441
2   phi3:mini           3145

In [40]:
theme_df = pd.DataFrame({
    "Theme":[
        "Education",
        "Health",
        "Inequality",
        "Economy",
        "Gender",
        "Climate",
        "Employment"
    ],
    "Score":[8,10,6,7,5,2,4]
})

theme_df

        Theme  Score
0   Education      8
1      Health     10
2  Inequality      6
3     Economy      7
4      Gender      5
5     Climate      2
6  Employment      4

In [41]:
indicator_df = pd.DataFrame({
    "Indicator":[
        "HDI",
        "GDP Per Capita",
        "Literacy Rate",
        "Education Index",
        "Life Expectancy Index"
    ],
    "Value":[
        0.756,
        2668.1,
        99.3,
        0.91,
        0.777
    ]
})

indicator_df

               Indicator     Value
0                    HDI     0.756
1         GDP Per Capita  2668.100
2          Literacy Rate    99.300
3        Education Index     0.910
4  Life Expectancy Index     0.777

In [42]:
theme_df.to_csv(
    "../outputs/theme_distribution.csv",
    index=False
)

indicator_df.to_csv(
    "../outputs/indicator_values.csv",
    index=False
)

In [43]:
evaluation_df = pd.DataFrame({
    "Metric":[
        "Consistency",
        "Completeness",
        "Factual Alignment"
    ],
    "Score":[4,4,4]
})

evaluation_df

              Metric  Score
0        Consistency      4
1       Completeness      4
2  Factual Alignment      4

In [44]:
evaluation_df.to_csv(
    "../outputs/evaluation_scores.csv",
    index=False
)

In [36]:
comparison_df.to_csv(
    "../outputs/model_comparison.csv",
    index=False
)

In [37]:
hdi_df = pd.DataFrame({
    "Year":[1995,2000,2001,2002,2003,2004],
    "HDI":[0.715,0.736,0.740,0.742,0.747,0.756]
})

In [38]:
life_df = pd.DataFrame({
    "Year":[1995,2000,2001,2002,2003,2004],
    "LifeExpectancy":[69.1,70.8,71.3,71.2,71.6,72.5]
})

In [45]:
gdi_df = pd.DataFrame({
    "Year":[1995,2000,2001,2002,2003,2004],
    "GDI":[0.704,0.729,0.734,0.738,0.742,0.752]
})

In [53]:
results_overview = pd.DataFrame({
    "Metric":[
        "HDI",
        "GDP Per Capita",
        "Literacy Rate",
        "Education Index",
        "Life Expectancy Index"
    ],
    "Value":[
        0.756,
        2668.1,
        99.3,
        0.91,
        0.777
    ]
})

results_overview

                  Metric     Value
0                    HDI     0.756
1         GDP Per Capita  2668.100
2          Literacy Rate    99.300
3        Education Index     0.910
4  Life Expectancy Index     0.777

In [54]:
results_overview.to_csv(
    "../outputs/results_overview.csv",
    index=False
)

In [46]:
print("\n===== REPORT SUMMARY =====")
print(report_summary)

print("\n===== THEME SCORES =====")
print(theme_scores)

print("\n===== INDICATORS =====")
print(indicators)

print("\n===== STRENGTHS & CHALLENGES =====")
print(strengths_challenges)

print("\n===== EVALUATION =====")
print(evaluation)

===== REPORT SUMMARY =====
Here are the requested items based on the provided context:

**Executive Summary (150 words maximum)**

The Republic of Uzbekistan's health care system is undergoing significant reforms, guided by principles of universal access, free primary health care, and improved quality of rural health services. The government has established new institutions, such as rural doctors' posts, to replace traditional medical attendants and provide better healthcare to rural populations. The 2006 "Year of Charity and Health Workers" aimed to enhance public health through integrated goal-oriented functions, focusing on preventive health care, healthy lifestyles, and improved quality of healthcare services. Despite retaining elements from the Soviet system, Uzbekistan's new system incorporates modern reforms, emphasizing human development and accessibility.

**Five Key Findings**

1. **Universal Access**: The government aims to provide universal access to primary health care, regardless of socioeconomic status or location.
2. **Rural Health Services Improvement**: New rural doctors' posts are being created to replace traditional medical attendants and improve healthcare quality in rural areas.
3. **Integration of Preventive Health Care**: The 2006 "Year of Charity and Health Workers" emphasized the importance of preventive health care, healthy lifestyles, and improved quality of healthcare services.
4. **Combination of Soviet and Modern Reforms**: Uzbekistan's new system retains features from the Soviet era while incorporating modern reforms to enhance human development and accessibility.
5. **Establishment of Specialized Centers**: Four national specialized centers for surgery, cardiology, urology, and microsurgery have been established in Uzbekistan.

**Five Key Policy Priorities**

1. **Strengthen Rural Health Services**: Improve the quality and accessibility of healthcare services in rural areas through the expansion of rural doctors' posts.
2. **Enhance Preventive Health Care**: Increase investments in preventive health care, healthy lifestyles, and disease prevention programs to reduce the burden of non-communicable diseases.
3. **Promote Universal Access to Primary Health Care**: Ensure that primary health care is free-of-charge and accessible to all population groups, regardless of socioeconomic status or location.
4. **Improve Quality of Healthcare Services**: Enhance the quality of healthcare services through training, capacity building, and infrastructure development.
5. **Address Chronic Alcohol and Drug Addiction**: Implement effective policies to address chronic alcohol and drug addiction, as outlined in Law No. 753-XII of 1992.

Please note that these points are based on the provided context and may not be exhaustive or up-to-date.

===== THEME SCORES =====
{
"education":8,
"health":10,
"inequality":6,
"economy":7,
"gender":5,
"climate":2,
"employment":4
}

===== INDICATORS =====
{"HDI":0.694,"Life_Expectancy":"72.5","Literacy_Rate":"","GDP_Per_Capita":"","Population":"","GDI":"","Women_Empowerment_Index":""}

===== STRENGTHS & CHALLENGES =====
```
{
  "development_strengths": [
    "Improvements in access to clean water",
    "Reduced child mortality rates",
    "Increased life expectancy",
    "Advances in education",
    "Growing income and economic growth",
    "Improved healthcare systems",
    "Enhanced social services",
    "Increased participation in sports and physical activities"
  ],
  "development_challenges": [
    "High levels of poverty and inequality",
    "Micronutrient deficiencies and malnutrition",
    "Environmental degradation and pollution",
    "Limited access to quality education",
    "Insufficient healthcare infrastructure",
    "Vicious cycle of poverty and poor health",
    "Lack of access to clean water and sanitation",
    "Inadequate healthcare services for vulnerable populations"
  ]
}
```

===== EVALUATION =====
{
  "consistency": 4,
  "completeness": 4,
  "factual_alignment": 4
}